# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT bobcard.wsgi

# beta_settings:
#     cloud_sql_instances: bobcard-224603:us-central1:bobcard

# runtime_config:
#   python_version: 3
# [END runtime]


# []
env_variables:
# the secret key used for the Django app (from PROJECT-DIRECTORY/settings.py)
  SECRET_KEY: 'DJANGO-SECRET-KEY' 
  DEBUG: 'False' # always False for deployment
  
# everything after /cloudsql/ can be found by entering >> gcloud sql instances describe DATABASE-NAME << in your Terminal
# the DATABASE-NAME is the name you gave your project's PostgreSQL database
# the second line from the describe output called connectionName can be copied and pasted after /cloudsql/
  DB_HOST: '/cloudsql/bobcard-224603:us-central1:bobcard'
  DB_PORT: '5432' # PostgreSQL port
  DB_NAME: 'bobcard'
  DB_USER: 'admin' # either 'postgres' (default) or one you created on the PostgreSQL instance page
  DB_PASSWORD: ' bobcard!'
  
  STATIC_URL: 'https://storage.googleapis.com/bobcard/static/'
  
handlers:
- url: /static
  static_dir: static

beta_settings:
# from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: bobcard-224603:us-central1:bobcard

runtime_config:
  python_version: 3 