# Generated by Django 2.1.3 on 2018-12-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyu_bobcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='net_id',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
