# Generated by Django 2.1.3 on 2018-12-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyu_bobcard', '0002_student_net_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studententry',
            name='net_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
