# Generated by Django 2.1.3 on 2018-12-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyu_bobcard', '0003_studententry_net_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studententry',
            old_name='requested_time',
            new_name='end_time',
        ),
    ]
