# Generated by Django 2.1.3 on 2018-12-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyu_bobcard', '0004_auto_20181207_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='net_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
