# Generated by Django 2.1.3 on 2018-12-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyu_bobcard', '0005_auto_20181207_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='location',
        ),
    ]
