# Generated by Django 2.1.3 on 2018-12-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nyu_bobcard', '0006_remove_student_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studententry',
            name='student',
        ),
        migrations.AlterField(
            model_name='studententry',
            name='net_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyu_bobcard.Student'),
        ),
    ]
